- user: yoda #Run as user yoda
  command_description: run at reboot a whoami #Short description of what the job does
  period: "@reboot" #When will the job be run (following schedule expressions)
  command: whoami #Command to execute
