name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20' # Specify the Go version you want to use

      - name: Install GoReleaser
        run: go install github.com/goreleaser/goreleaser@latest

      - name: Build and Release
        run: goreleaser --clean
